### ISSUE TITLE
forward_llama() missing 1 required keyword-only argument: 'rotary_values'

### ISSUE THREAD

**Issue by GluckLee** [ayaka14732/llama-2-jax#16]
File "d:\code\llama-2-jax\train.py", line 140, in <module>
    main()
  File "d:\code\llama-2-jax\train.py", line 130, in main
    params, opt_state, total_loss, loss, key = train_step(params, opt_state, total_loss, data_batch, key)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\code\llama-2-jax\train.py", line 68, in train_step
    loss, grads = train_forward(params, data_batch, key=subkey)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\code\llama-2-jax\train.py", line 61, in train_forward
    logits = forward_llama(params, seq, seq_mask, key=key, model_config=model_config_llama2_7B)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: forward_llama() missing 1 required keyword-only argument: 'rotary_values'

**Comment by ayaka14732** [comment]
Sorry for that. Going to fix it within 24 hrs.

**Comment by ayaka14732** [comment]
This should be fixed now.
