### ISSUE TITLE
Adapt the repo for Mistral. Also error in calculation of `d_k` in `determine_params.py`

### ISSUE THREAD

**Issue by defdet** [ayaka14732/llama-2-jax#21]
I'm trying to adapt this implementation of LLaMA to Mistral. According to the Mistral's [paper](https://arxiv.org/abs/2310.06825), the only meaningfull difference is Sliding Window Attention (SWA). The way I understand it, if `max_len` is lower than the sliding window size (4096), attention mechanism should be identical to LLaMA's, so adapting should be a piece of cake. We should only change the model config. In while doing so, I faced/noticed the following:
1) Formula for `d_k` in `determine_params.py` is incorrect. It currently is `q_size / (d_m * kv_heads)` and should be `q_size / (d_m * num_heads)` or `k_size / (d_m * kv_heads)`. Am currently trying to figure out how to create a pull request.
2) With adapted config (will be presented as the next message for the ease of reading) the model generates gibberish beyond the reach of God (like '/n/n/n/n/n nature bekon'). I've been trying to figure out why for about half a month now to no avail.
I was wondering, as author of this implementation, could you advise why this is happening? (made sure that prompt formatting is correct and new model config is applied everywhere throughout the code). Any suggestions would be appreciated.

**Comment by defdet** [comment]
Model config:
mistral_config = ModelConfig(
    d_ff=14336,
    d_k=128,
    d_model=4096,
    d_v=128,
    n_heads_kv=8,
    n_layers=32,
    n_rep_kv=4,
    rms_norm_eps=1e-5,
    token_id_bos=1,
    token_id_eos=2,
    token_id_pad=0,
    vocab_size=32000,
    dropout_rate=None,
    return_kv_cache=False,
). By the way, I tested and LLaMA implementation works on Kaggle TPU.

**Comment by ayaka14732** [comment]
I am currently collaborating with @yixiaoer on implementing the JAX version of the Mistral model: https://github.com/yixiaoer/mistral-jax

**Comment by ayaka14732** [comment]
> 1) Formula for `d_k` in `determine_params.py` is incorrect. It currently is `q_size / (d_m * kv_heads)` and should be `q_size / (d_m * num_heads)` or `k_size / (d_m * kv_heads)`. Am currently trying to figure out how to create a pull request.

You are right.

https://github.com/ayaka14732/llama-2-jax/blob/main/scripts/determine_params.py#L17C19-L17C19

```
k = q_size // m // h
```

should be

```
k = k_size // m // h
```

**Comment by ayaka14732** [comment]
https://github.com/ayaka14732/llama-2-jax/blob/main/lib/llama_params/convert_params.py#L16

```python
def convert_q_proj(x: tnn.Linear, *, model_config: ModelConfig) -> Array:
    return pt2jax(x.weight.T.reshape(model_config.d_model, model_config.n_rep_kv, model_config.n_heads_kv, model_config.d_k))

def convert_out_proj(x: tnn.Linear, *, model_config: ModelConfig) -> Array:
    return pt2jax(x.weight.T.reshape(model_config.n_rep_kv, model_config.n_heads_kv, model_config.d_v, model_config.d_model))
```

Yesterday @yixiaoer and I found that in the Mistral model, `model_config.n_rep_kv, model_config.n_heads_kv` may need to be changed to `model_config.n_heads_kv, model_config.n_rep_kv` to get the correct result.

**Comment by defdet** [comment]
Thank's a lot for this stellar advice! I implemented what you said and now the model generates text just fine. Looking forward to yours and @yixiaoer implementation of Mistral!

**Comment by ayaka14732** [comment]
> > 1. Formula for `d_k` in `determine_params.py` is incorrect. It currently is `q_size / (d_m * kv_heads)` and should be `q_size / (d_m * num_heads)` or `k_size / (d_m * kv_heads)`. Am currently trying to figure out how to create a pull request.
> 
> You are right.
> 
> https://github.com/ayaka14732/llama-2-jax/blob/main/scripts/determine_params.py#L17C19-L17C19
> 
> ```
> k = q_size // m // h
> ```
> 
> should be
> 
> ```
> k = k_size // m // h
> ```

@defdet Can you make a PR for this?
